version: "3.9"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - delulu
  
  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.0
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - delulu

volumes:
  grafana-data:

networks:
  delulu:
    driver: bridge